import {setupOnline,enterOnline} from './online.js';
const APP_VERSION='0.1.15';
import {showMap,locatorPosition} from './map.js';
import {bands,modes,bandFor,validate,exportADIF,parseADIF,fingerprint} from './adif.js';
const $=id=>document.getElementById(id), form=$('contactForm'), profileForm=$('profileForm');
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let db,state={contacts:[],profiles:[],active:null},editing=null,editingProfile=null,busy=false;
function notice(message){$('notice').textContent=message;$('notice').hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('notice').hidden=true,6500);}
async function safe(fn){try{await fn();}catch(e){console.error(e);notice(e.message||'Não foi possível concluir a operação.');}}
function openDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('ct7asy-logbook-web',1);request.onupgradeneeded=()=>request.result.createObjectStore('state');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('Não foi possível abrir o armazenamento deste dispositivo.'));});}
function readState(){return new Promise((resolve,reject)=>{const tx=db.transaction('state');const req=tx.objectStore('state').get('logbook');req.onsuccess=()=>resolve(req.result||{contacts:[],profiles:[],active:null});req.onerror=()=>reject(req.error);});}
// Read and write inside one IndexedDB transaction, including across open tabs.
async function mutate(change){if(busy)throw Error('A guardar. Aguarda um momento.');busy=true;try{state=await new Promise((resolve,reject)=>{const tx=db.transaction('state','readwrite'),store=tx.objectStore('state'),req=store.get('logbook');let next;req.onsuccess=()=>{try{next=req.result||{contacts:[],profiles:[],active:null};change(next);store.put(next,'logbook');}catch(e){reject(e);tx.abort();}};tx.oncomplete=()=>resolve(next);tx.onerror=()=>reject(tx.error||Error('Não foi possível guardar. Faz uma cópia de segurança.'));tx.onabort=()=>reject(tx.error||Error('Operação cancelada.'));});render();channel?.postMessage('refresh');}finally{busy=false;}}
const channel='BroadcastChannel' in window?new BroadcastChannel('ct7asy-web'):null;
if(channel)channel.onmessage=()=>safe(async()=>{state=await readState();render();});
const active=()=>state.profiles.find(p=>p.id===state.active);
const kind=p=>/^(CT[0Ø]|SWL)/i.test(p?.station||'')?'SWL':'QSO';
function options(el,values){el.innerHTML=values.map(v=>`<option value="${esc(v)}">${esc(v||'Selecionar')}</option>`).join('');}
options(form.elements.mode,modes);
let manualTime=false;
const pad=n=>String(n).padStart(2,'0');
function localFields(date){return {date:date.getFullYear()+'-'+pad(date.getMonth()+1)+'-'+pad(date.getDate()),time:pad(date.getHours())+':'+pad(date.getMinutes())};}
function setLocalTime(date){const parts=localFields(date);form.elements.date.value=parts.date;form.elements.time.value=parts.time;syncUTC();}
function contactInstant(){
 const date=form.elements.date.value,time=form.elements.time.value,old=state.contacts.find(c=>c.id===editing);
 // Preserve the exact instant (and seconds) when editing, including repeated DST hours.
 if(old){const instant=new Date(old.date+'T'+old.time+'Z'),local=localFields(instant);if(date===local.date&&time===local.time)return instant;}
 const instant=new Date(date+'T'+time+':00');
 if(!date||!time||!Number.isFinite(instant.getTime()))return null;
 const local=localFields(instant);return local.date===date&&local.time===time?instant:null;
}
function syncUTC(){const instant=contactInstant();$('contactUTC').value=instant?instant.toISOString().slice(11,16):'';$('contactUTC').title=instant?'Data UTC: '+instant.toISOString().slice(0,10):'';}
for(const field of ['date','time'])form.elements[field].oninput=()=>{manualTime=true;syncUTC();};
setInterval(()=>{if(!editing&&!manualTime)setLocalTime(new Date());},1000);
function reset(){editing=null;manualTime=false;form.reset();setLocalTime(new Date());$('formTitle').textContent='Registo de contacto';$('saveContact').textContent='Guardar contacto';renderProfileHint();}
function renderProfileHint(){const p=active();$('activeProfile').textContent=p?p.station+' · '+p.locator:'Sem perfil';$('profileHint').textContent=editing?'A editar: os dados da estação deste contacto serão mantidos.':p?'Estação: '+p.station+' · '+p.locator:'Cria e seleciona um perfil antes de guardar contactos.';$('kindBadge').textContent=kind(p)==='SWL'?(/^CT[0Ø]/i.test(p.station)?'CTØ':'SWL'):'QSO';}
function navigate(id){document.querySelectorAll('.page').forEach(el=>el.hidden=el.id!==id);document.querySelectorAll('nav button').forEach(b=>{if(b.dataset.page===id)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});window.scrollTo(0,0);if(id==='map')requestAnimationFrame(()=>showMap(state,active()));if(['dx','propagation'].includes(id))enterOnline(id);}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.page));
function render(){renderProfileHint();renderHistory();renderProfiles();renderExport();if(!$('map').hidden)showMap(state,active());}
function renderHistory(){const q=$('search').value.trim().toLowerCase();const list=state.contacts.filter(c=>[c.call,c.name,c.qth,c.country].some(v=>(v||'').toLowerCase().includes(q))).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));$('contactCount').textContent=state.contacts.length+(state.contacts.length===1?' contacto':' contactos');$('contactList').innerHTML=list.map(c=>`<article class="card"><div class="history-summary"><strong>${esc(c.call)}</strong><span>${esc(c.date.split('-').reverse().join('-'))}</span><span>${esc(c.time)} UTC</span><span>${esc(c.band)} · ${esc(c.mode)}</span>${c.name||c.qth?`<span>${esc(c.name||c.qth)}</span>`:''}<span>Estação: ${esc(c.station||'—')}</span></div><div class="actions"><button data-edit="${c.id}">Editar</button><button data-delete="${c.id}">Apagar</button></div></article>`).join('')||'<p class="muted">Ainda não há contactos para apresentar.</p>';}
$('search').oninput=renderHistory;
form.elements.call.oninput=e=>e.target.value=e.target.value.toUpperCase();
form.elements.freq.oninput=()=>{form.elements.band.value=bandFor(form.elements.freq.value.trim().replace(',','.'));};
form.elements.freq.onchange=()=>{form.elements.freq.value=form.elements.freq.value.trim().replace(',','.');form.elements.freq.oninput();};
form.addEventListener('keydown',e=>{
 if(e.key!=='Enter'||e.isComposing||e.keyCode===229)return;
 if(!e.target.matches('input,select,textarea'))return;
 if(e.target.tagName==='TEXTAREA'&&e.shiftKey)return;
 e.preventDefault();
 const fields=[...form.querySelectorAll('input,select,textarea')].filter(el=>!el.disabled&&!el.readOnly&&el.type!=='hidden');
 const index=fields.indexOf(e.target);
 (fields[(index+1)%fields.length])?.focus();
});
form.onsubmit=e=>{e.preventDefault();safe(async()=>{const p=active(),old=state.contacts.find(c=>c.id===editing);if(!old&&!p){navigate('profiles');throw Error('Cria primeiro o perfil da tua estação.');}const c=Object.fromEntries(new FormData(form));c.call=c.call.trim().toUpperCase();c.locator=old?.locator||'';const instant=contactInstant();if(!instant)throw Error('Data ou hora local inválida.');const utc=instant.toISOString();c.date=utc.slice(0,10);c.time=utc.slice(11,19);c.freq=c.freq.trim().replace(',','.');c.band=c.freq?bandFor(c.freq):c.band;Object.assign(c,{id:old?.id||crypto.randomUUID(),station:old?old.station:p.station,station_locator:old?old.station_locator:p.locator,kind:old?old.kind:kind(p),profileId:old?old.profileId:p.id});validate(c);await mutate(s=>{if(old){const i=s.contacts.findIndex(x=>x.id===c.id);if(i<0)throw Error('Este contacto foi removido noutra janela.');s.contacts[i]=c;}else s.contacts.push(c);});reset();notice('Contacto guardado neste dispositivo.');form.elements.call.focus();});};
$('clearContact').onclick=()=>{reset();form.elements.call.focus();};
$('contactList').onclick=e=>safe(async()=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const c=state.contacts.find(c=>c.id===edit.dataset.edit);form.reset();editing=c.id;for(const k of ['mode'])if(![...form.elements[k].options].some(o=>o.value===c[k]))form.elements[k].add(new Option(c[k],c[k]));for(const [k,v]of Object.entries(c))if(form.elements[k])form.elements[k].value=k==='time'?v.slice(0,5):v;manualTime=true;setLocalTime(new Date(c.date+'T'+c.time+'Z'));if(c.freq)form.elements.band.value=bandFor(c.freq);$('formTitle').textContent='Editar contacto';$('saveContact').textContent='Guardar alterações';renderProfileHint();navigate('log');}if(del&&confirm('Apagar este contacto? Esta ação não pode ser anulada.'))await mutate(s=>{s.contacts=s.contacts.filter(c=>c.id!==del.dataset.delete);});});
function renderProfiles(){$('profileList').innerHTML=state.profiles.map(p=>`<article class="card"><label class="profile-choice"><input type="radio" name="activeStation" value="${p.id}" ${p.id===state.active?'checked':''}><span><strong>${esc(p.station)}</strong><br>${esc(p.locator)}</span></label><div class="actions"><button data-profile-edit="${p.id}">Editar</button><button data-profile-delete="${p.id}">Apagar</button></div></article>`).join('')||'<p class="muted">Adiciona o teu primeiro perfil.</p>';}
$('profileList').onchange=e=>safe(()=>mutate(s=>{if(s.profiles.some(p=>p.id===e.target.value))s.active=e.target.value;}));
function clearProfile(){editingProfile=null;profileForm.reset();$('profileFormTitle').textContent='Novo perfil';}
$('cancelProfile').onclick=clearProfile;
profileForm.onsubmit=e=>{e.preventDefault();safe(async()=>{const station=profileForm.elements.station.value.trim().toUpperCase(),locator=profileForm.elements.locator.value.trim().toUpperCase();if(!/^[A-Z0-9/\-]{2,30}$/.test(station))throw Error('Indicativo inválido.');if(!/^[A-R]{2}\d{2}(?:[A-X]{2}(?:\d{2}(?:[A-X]{2})?)?)?$/.test(locator))throw Error('Locator inválido (4, 6, 8 ou 10 caracteres).');const p={id:editingProfile||crypto.randomUUID(),station,locator};await mutate(s=>{if(s.profiles.some(x=>x.id!==p.id&&x.station===station&&x.locator===locator))throw Error('Este perfil já existe.');const i=s.profiles.findIndex(x=>x.id===p.id);if(editingProfile&&i<0)throw Error('Este perfil já foi removido.');if(i>=0)s.profiles[i]=p;else s.profiles.push(p);if(!s.active)s.active=p.id;});clearProfile();notice('Perfil guardado.');});};
$('profileList').onclick=e=>safe(async()=>{const edit=e.target.closest('[data-profile-edit]'),del=e.target.closest('[data-profile-delete]');if(edit){const p=state.profiles.find(x=>x.id===edit.dataset.profileEdit);editingProfile=p.id;profileForm.elements.station.value=p.station;profileForm.elements.locator.value=p.locator;$('profileFormTitle').textContent='Editar perfil';profileForm.scrollIntoView({behavior:'smooth'});}if(del&&confirm('Apagar o perfil? Os contactos existentes serão mantidos.')){await mutate(s=>{s.profiles=s.profiles.filter(p=>p.id!==del.dataset.profileDelete);if(s.active===del.dataset.profileDelete)s.active=s.profiles[0]?.id||null;});clearProfile();}});
function renderExport(){const selected=new Set([...$('exportChoices').querySelectorAll('input:checked')].map(x=>x.value));$('exportChoices').innerHTML=state.contacts.map(c=>`<label class="export-choice"><input type="checkbox" value="${c.id}" ${selected.has(c.id)?'checked':''}>${esc(c.call)} · ${esc(c.date)} · ${esc(c.band)}</label>`).join('')||'<p>Sem contactos.</p>';}
$('exportScope').onchange=()=>$('exportChoices').hidden=$('exportScope').value!=='selected';
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('exportAdif').onclick=()=>safe(async()=>{const ids=new Set([...$('exportChoices').querySelectorAll('input:checked')].map(x=>x.value));const list=state.contacts.filter(c=>$('exportScope').value==='all'||ids.has(c.id));if(!list.length)throw Error('Seleciona pelo menos um contacto.');const name='CT7ASY-'+new Date().toISOString().slice(0,10)+'.adi',text=exportADIF(list),file=new File([text],name,{type:'application/octet-stream'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file]});notice('Ficheiro ADIF entregue à opção escolhida.');}catch(e){if(e.name!=='AbortError')throw e;}}else{download(text,name,'application/octet-stream');notice('ADIF preparado com extensão .adi.');}});
async function readFile(input){const f=input.files[0];if(!f)return null;if(f.size>10*1024*1024)throw Error('O limite deste protótipo é 10 MB por ficheiro.');return f.text();}
$('importFile').onchange=()=>safe(async()=>{$('importPreview').replaceChildren();const text=await readFile($('importFile'));if(text===null)return;const list=parseADIF(text),known=new Set(state.contacts.map(fingerprint));let duplicates=0;for(const c of list){const key=fingerprint(c);if(known.has(key))duplicates++;else known.add(key);}$('importPreview').innerHTML=`<p>${list.length} contactos lidos. ${duplicates} duplicados exatos. ${list.filter(c=>!c.freq).length} sem frequência (serão preservados assim).</p><button id="confirmImport" class="primary">Confirmar importação</button>`;$('confirmImport').onclick=()=>safe(async()=>{let added=0;await mutate(s=>{const keys=new Set(s.contacts.map(fingerprint));for(const c of list){const key=fingerprint(c);if(!keys.has(key)){keys.add(key);s.contacts.push({...c,id:crypto.randomUUID()});added++;}}});$('importPreview').textContent=added+' contactos importados.';$('importFile').value='';notice('Importação concluída.');});});
$('backup').onclick=()=>safe(async()=>{state=await readState();download(JSON.stringify({format:'ct7asy-web',version:1,created:new Date().toISOString(),state},null,2),'CT7ASY-backup-'+new Date().toISOString().slice(0,10)+'.json','application/json');});
$('restoreFile').onchange=()=>safe(async()=>{const text=await readFile($('restoreFile'));if(text===null)return;const data=JSON.parse(text);if(data.format!=='ct7asy-web'||data.version!==1||!Array.isArray(data.state?.contacts)||!Array.isArray(data.state?.profiles))throw Error('Cópia de segurança incompatível.');const restored=data.state,ids=new Set();for(const c of restored.contacts){validate(c);if(typeof c.id!=='string'||!c.id||ids.has(c.id)||!/^[-\w]+$/.test(c.id))throw Error('Identificadores de contactos inválidos.');ids.add(c.id);}ids.clear();for(const p of restored.profiles){if(typeof p.id!=='string'||!/^[-\w]+$/.test(p.id)||ids.has(p.id)||!p.station||!p.locator)throw Error('Perfis inválidos.');ids.add(p.id);}if(restored.active&&!ids.has(restored.active))throw Error('Perfil ativo inválido.');if(!confirm(`Restaurar ${restored.contacts.length} contactos e ${restored.profiles.length} perfis? Os dados atuais deste dispositivo serão substituídos. Guarda uma cópia antes de continuar.`))return;await mutate(s=>Object.assign(s,{contacts:restored.contacts,profiles:restored.profiles,active:restored.active||null}));reset();clearProfile();$('restoreFile').value='';notice('Cópia restaurada.');});
if($('appVersion'))$('appVersion').textContent=APP_VERSION;
function connection(){$('connection').textContent=navigator.onLine?'Ligação disponível':'Sem Internet · modo local';}addEventListener('online',connection);addEventListener('offline',connection);
setupOnline({profile:active,contacts:()=>state.contacts,navigate,toLog:spot=>{if((form.elements.call.value||editing)&&!confirm('Substituir o contacto em edição pelo spot selecionado?'))return;reset();form.elements.call.value=spot.call;form.elements.freq.value=String(spot.freq);form.elements.band.value=bandFor(spot.freq);if(spot.mode){if(![...form.elements.mode.options].some(o=>o.value===spot.mode))form.elements.mode.add(new Option(spot.mode,spot.mode));form.elements.mode.value=spot.mode;}else{form.elements.mode.selectedIndex=-1;}navigate('log');notice('Spot colocado no Log. Confirme o modo e os restantes dados.');}});
options($('dxBand'),['',...bands]);options($('dxMode'),['',...modes]);$('dxBand').options[0].textContent='Todas';$('dxMode').options[0].textContent='Todos';
await safe(async()=>{db=await openDB();state=await readState();reset();render();connection();if(navigator.storage?.persist)await navigator.storage.persist().catch(()=>false);});
if('serviceWorker' in navigator&&isSecureContext){navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(()=>navigator.serviceWorker.ready).then(()=>$('offlineStatus').textContent='Disponível sem Internet neste dispositivo após a primeira abertura.').catch(()=>$('offlineStatus').textContent='Não foi possível preparar o modo sem Internet. Volta a abrir com ligação.');}else $('offlineStatus').textContent='Para instalar e funcionar sem Internet, abre a aplicação num endereço HTTPS.';
